### ISSUE TITLE
massive CPU usage

### ISSUE THREAD

**Issue by x37v** [openAVproductions/openAV-Fabla#51] opened 2018-10-13 22:09 UTC
I'm running fabla on a modern PC and fabla [via jalv.gtk] uses about 75% of my cpu. On top of that, Xorg uses about 81% when fabla is running. This is not the case with other lv2 plugins I've run with jalv.

I've verified that this also happens with fabla in ardour.

seems like its likely a GUI drawing thing?

**Comment by harryhaaren** [comment] 2018-12-15 07:57
Yes ack it probably is something going wrong with redraws being issued too often. This will require a bit of debug, i'll try to get around to it once the LAC submission deadline is gone by! Thanks for reporting

**Comment by harryhaaren** [comment] 2021-03-28 19:01
Cannot reproduce this, marking as closed. Please re-open with more details on how to reproduce if this issue still exists.

**Closed by harryhaaren** 2021-03-28 19:01 UTC
Labels: bug
